# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [6]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)

print('list(a): ', list(a))
print('list(a): ', type(list(a)[0]),'list只處理最外層(第一維)，剩下都還是numpy')
print('tolist(): ', a.tolist())
print('tolist(): ', type(a.tolist()[0]),'tolist是直接轉換成list')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
list(a):  [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
list(a):  <class 'numpy.ndarray'> list只處理最外層(第一維)，剩下都還是numpy
tolist():  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
tolist():  <class 'list'> tolist是直接轉換成list


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [ ]:
# 記得先 Import 正確的套件

'''
Your Code
'''

In [7]:
a = np.random.randint(10, size=6) 
print('ndim：',a.ndim)      # 確認維度
print('shape：',a.shape)    # 維度大小 
print('size：',a.size)      # 幾個元素
print('dtype：',a.dtype)    # 資料型態
print('itemsize：',a.itemsize)  # 每個元素佔的記憶體空間
print('data：',a.data)      # 記憶體位置
print('sum：',a.sum())      # 所有元素總和

ndim： 1
shape： (6,)
size： 6
dtype： int32
itemsize： 4
data： <memory at 0x000001F0BB302E00>
sum： 41


In [8]:
b = np.random.randint(10, size=(3,4)) 

print('ndim：',b.ndim)      # 確認維度
print('shape：',b.shape)    # 維度大小 
print('size：',b.size)      # 幾個元素
print('dtype：',b.dtype)    # 資料型態
print('itemsize：',b.itemsize)  # 每個元素佔的記憶體空間
print('data：',b.data)      # 記憶體位置
print('sum：',b.sum())      # 所有元素總和

ndim： 2
shape： (3, 4)
size： 12
dtype： int32
itemsize： 4
data： <memory at 0x000001F0AFE99B10>
sum： 42


In [9]:
c = np.random.randint(10, size=(2,3,2)) 

print('ndim：',c.ndim)      # 確認維度
print('shape：',c.shape)    # 維度大小 
print('size：',c.size)      # 幾個元素
print('dtype：',c.dtype)    # 資料型態
print('itemsize：',c.itemsize)  # 每個元素佔的記憶體空間
print('data：',c.data)      # 記憶體位置
print('sum：',c.sum())      # 所有元素總和

ndim： 3
shape： (2, 3, 2)
size： 12
dtype： int32
itemsize： 4
data： <memory at 0x000001F0AFA558A0>
sum： 60


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [10]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[5, 5, 9, 5, 9, 4]
[5, 5, 9, 5, 9, 4]


In [11]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))

[[7, 7, 6, 6], [5, 0, 2, 9], [6, 6, 9, 3]]
[array([7, 7, 6, 6]), array([5, 0, 2, 9]), array([6, 6, 9, 3])]


In [14]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[7, 6], [9, 5], [6, 1]], [[2, 8], [8, 5], [2, 2]]]
[array([[7, 6],
       [9, 5],
       [6, 1]]), array([[2, 8],
       [8, 5],
       [2, 2]])]


In [31]:
def tolist(iterable):
    if iterable.ndim == 1:
        return list(iterable)
    else:
        return iterable.tolist()
    

print(tolist(a))
print(type(tolist(a)[0]))
print(tolist(b))
print(type(tolist(b)[0]))
print(tolist(c))
print(type(tolist(c)[0]))

[5, 5, 9, 5, 9, 4]
<class 'numpy.int32'>
[[7, 7, 6, 6], [5, 0, 2, 9], [6, 6, 9, 3]]
<class 'list'>
[[[7, 6], [9, 5], [6, 1]], [[2, 8], [8, 5], [2, 2]]]
<class 'list'>
