# [作業目標]

1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```

2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？

3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

# 作業 

### 1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```


In [ ]:
import numpy as np

a = np.array([20, 30, 40, 50])
b = np.array([1, 2, 3, 4])
c = 1
d = np.array([1])
e = np.array([1, 2])

print(a + a)  # [40 60 80 100]

print(a + b)  # [21 32 43 54]

print(a + c)  # [21 31 41 51]

print(a + d)  # [21 31 41 51]

print(a + e)  # 失敗

[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

### 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？


In [1]:
# 記得先 Import 正確的套件

import numpy as np

In [3]:
A = np.ones(3) * 1
B = np.ones(3) * 2
C = (A + B) * (-A / 2)
print(A)
print(B)
print(C)

[1. 1. 1.]
[2. 2. 2.]
[-1.5 -1.5 -1.5]


In [20]:
# 迴圈
answer_1 = np.zeros(3)
answer_2 = np.zeros(3)
for i in range(A.shape[0]):
    answer_1[i] = A[i] + B[i]
    answer_2[i] = (-A[i])/2
C = answer_1*answer_2
print(C)

[-1.5 -1.5 -1.5]


### 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？


In [31]:
A = np.ones((1, 6))
B = np.ones((6, 1))


AB_dot = np.dot(A,B)
print('內積：',AB_dot)

AB_outer = np.outer(A,B)
print('外積：','\n',AB_outer)


內積： [[6.]]
外積： 
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [26]:
# [作業目標]

1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```

2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？

3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

# 作業 

### 1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```




### 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？


A = np.ones(3)*1
B = np.ones(3)*2

print((A + B) * (-A / 2))

### 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？


# 記得先 Import 正確的套件

import numpy as np


# 參考解答

A = np.ones((1,6))
B = np.ones((6,1))

print(A * B)
print(A @ B)





SyntaxError: invalid character '，' (U+FF0C) (2179468361.py, line 3)