# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [ ]:
# np.zeros 是創指定形狀的陣列，但是值都是0
# np.empty 是創指定形狀的陣列，但是裡面的值是隨機的

'\nYour Code\n'

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [1]:
# 記得先 Import 正確的套件
import numpy as np

In [ ]:
# 參考解答
# 方法一 ： 直接轉成整數，無條件捨去法
a = np.random.rand(2, 3)
a = a.astype(int)
print(a)

# 方法二： 乘某一個倍數後之後取整數
b = np.random.rand(2, 3)
b = (b * 10).astype(int)
print(b)

[[0 0 0]
 [0 0 0]]
[[0 9 1]
 [3 0 6]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [ ]:
m = 20
n = 40
a = np.random.rand(2, 3)


# 使用線性縮放公式：a_scaled = a * (max - min) + min

a = (a * (40 - 20) + 20).astype(int)
print(a)

[[23 29 39]
 [36 21 25]]
