# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [ ]:
# 記得先 Import 正確的套件
import numpy as np 

'\nYour Code\n'

In [ ]:
a = np.arange(11)
print(a)

#  方法一：迴圈
b = np.zeros(11)
for i in range (a.shape[0]):
    if 7 > i > 2 :
        b[i] = -(i)
    else:
        b[i] = (i)
print(b)




[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0.  1.  2. -3. -4. -5. -6.  7.  8.  9. 10.]


In [13]:
# 方法二：直接轉
c = np.arange(11)

c[(3<=c) & (c<=6)] *=-1
print(c)

[ 0  1  2 -3 -4 -5 -6  7  8  9 10]


In [ ]:
# 方法三：np.where(<條件>,<符合條件的變成>,<不符合條件的變成>)
d = np.arange(11)

d = np.where([(3<=d)&(6>=d)],-d,d)
print(d)

[[ 0  1  2 -3 -4 -5 -6  7  8  9 10]]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [17]:
A = np.random.rand(3, 6)
print(A)
print(A[A>0.5])
print(A[A>0.5].size)


[[0.59729897 0.41057295 0.65660297 0.26226647 0.26102414 0.82307358]
 [0.95884237 0.97646531 0.83236472 0.66010274 0.71089649 0.23189791]
 [0.2541669  0.00311153 0.38762503 0.17361237 0.37059834 0.72860661]]
[0.59729897 0.65660297 0.82307358 0.95884237 0.97646531 0.83236472
 0.66010274 0.71089649 0.72860661]
9
