# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [ ]:
import numpy as np
a = np.arange(6)

print(a.sum())      # 這是 NumPy 陣列物件的方法，直接作用於陣列 a
print(np.sum(a))    # 這是 NumPy 模組中的函數，作用於傳入的數據
print(sum(a))       # 這是 Python 的內建函數，適用於任何可迭代對象

15
15
15


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [3]:
# 記得先 Import 正確的套件
import numpy as np

In [ ]:
# 最大值-最小值正規化：將矩陣中的數值縮放到 [0, 1] 或其他指定範圍
A = np.random.random((5, 5))
A_normalized = (A - A.min()) / (A.max()-A.min())
print(A_normalized)


[[0.03339993 0.         0.13531678 0.92571314 0.93220686]
 [0.33043627 0.49440318 0.64696294 0.55699507 0.47786016]
 [0.24499343 0.23113569 0.45249647 0.63284842 0.29804223]
 [0.37615749 1.         0.04467689 0.17879727 0.17913913]
 [0.45037433 0.76211852 0.62412691 0.4104343  0.04420048]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [ ]:
# 方法一：想到什麼就用什麼，但發現這個方法將順序調動了...
B = np.random.random(10)
B_sorted = np.sort(B)
B_sorted[9] = (-1)
print(B_sorted)

[ 0.10250437  0.10378951  0.27183495  0.32203297  0.46127534  0.47651399
  0.47944267  0.54345848  0.61459525 -1.        ]


In [81]:
# 方法二：使用np.argmax()
C = np.random.random(10)
# 找到最大值的索引
max_index = np.argmax(C)

# 將最大值改為 -1
C[max_index] = -1
print(C)

[ 0.941713    0.68096135  0.87369522  0.32382981  0.90162532  0.32376385
  0.33540708  0.78094206  0.68691592 -1.        ]
