In [1]:
import numpy as np

In [2]:
print(np) # <module 'numpy' from '.../numpy/__init__.py'>
print(np.__version__) # 1.20.1

<module 'numpy' from 'c:\\Users\\jerry\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\numpy\\__init__.py'>
1.26.4


In [4]:
a = np.arange(15).reshape(3,5)
print(a)
print(type(a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>


In [7]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
# print(a.itsize)
print(a.data)
print(a.sum)

2
(3, 5)
15
int32
<built-in method sum of numpy.ndarray object at 0x000002152D8C02D0>


In [9]:
list(a)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]

In [8]:
list(a)
# [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]

a.tolist()
# [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]