In [2]:
import numpy as np

In [3]:
# 檢查是否有安裝以及版本號
print(np) 
print(np.__version__) 

<module 'numpy' from 'c:\\Users\\jerry\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\numpy\\__init__.py'>
1.26.4


In [8]:
a = np.arange(15).reshape(3,5)
print(a)        # 印出陣列
print(type(a))  # 確認型態 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>


In [9]:
print('ndim：',a.ndim)      # 確認維度
print('shape：',a.shape)    # 維度大小 
print('size：',a.size)      # 幾個元素
print('dtype：',a.dtype)    # 資料型態
print('itemsize：',a.itemsize)  # 每個元素佔的記憶體空間
print('data：',a.data)      # 記憶體位置
print('sum：',a.sum())      # 所有元素總和

ndim： 2
shape： (3, 5)
size： 15
dtype： int32
itemsize： 4
data： <memory at 0x00000192DF8A5560>
sum： 105


In [9]:
print('list(a): ', list(a))
print('tolist(): ', a.tolist())

list(a):  [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
tolist():  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


In [10]:
print(type(list(a)[0]))
print(type(a.tolist()[0]))

<class 'numpy.ndarray'>
<class 'list'>
