# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [ ]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)

print('list(a): ', list(a),'list只處理最外層(第一維)，盛夏都還是numpy')
print('tolist(): ', a.tolist(),'tolist是直接轉換成list')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
list(a):  [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
tolist():  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [ ]:
# 記得先 Import 正確的套件

'''
Your Code
'''

In [ ]:
a = np.random.randint(10, size=6) 
print(a)
print(a.ndim)       #有幾維
print(a.shape)      #每個維度的大小
print(a.size)       #總共有幾個元素
print(a.dtype)      #資料型態
print(a.itemsize)   #每個元素所佔的記憶體空間
print(len(a))       #長度





[7 2 0 3 7 2]
1
(6,)
6
int32
4
6


In [ ]:
b = np.random.randint(10, size=(3,4)) 

print(b)
print(b.ndim)       #有幾維
print(b.shape)      #每個維度的大小
print(b.size)       #總共有幾個元素
print(b.dtype)      #資料型態
print(b.itemsize)   #每個元素所佔的記憶體空間
print(len(b))       #第一個維度的長度

[[7 0 6 9]
 [4 8 6 6]
 [9 4 7 2]]
2
(3, 4)
12
int32
4
3


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)
print(c.ndim)       #有幾維
print(c.shape)      #每個維度的大小
print(c.size)       #總共有幾個元素
print(c.dtype)      #資料型態
print(c.itemsize)   #每個元素所佔的記憶體空間
print(len(c))       #第一個維度的長度

[[[8 5]
  [1 9]
  [6 1]]

 [[9 9]
  [1 7]
  [2 5]]]
3
(2, 3, 2)
12
int32
4
2


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [ ]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[7, 6, 7, 3, 7, 5]
[7, 6, 7, 3, 7, 5]


In [ ]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))

[[6, 9, 4, 1], [4, 2, 7, 4], [0, 1, 6, 1]]
[array([6, 9, 4, 1]), array([4, 2, 7, 4]), array([0, 1, 6, 1])]
[array([6, 9, 4, 1]), array([4, 2, 7, 4]), array([0, 1, 6, 1])]


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
[array([[0, 4],
       [0, 1],
       [9, 5]]), array([[8, 7],
       [8, 2],
       [6, 0]])]


In [ ]:
def tolist(iterable):
    '''
    Your Code
    '''

print(tolist(a))
print(tolist(b))
print(tolist(c))

[7, 6, 7, 3, 7, 5]
[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]


[7, 6, 7, 3, 7, 5]
[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
