# 範例
***

# [教學目標]

* 能夠使用不同的方法初始化一個陣列
* 知道固定大小對於陣列的意義
* 了解不同的亂數陣列有什麼差異



In [12]:
# 載入 NumPy 套件
import numpy as np

# 檢查正確載入與版本
print(np)
print(np.__version__)

<module 'numpy' from 'c:\\Users\\jerry\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\numpy\\__init__.py'>
1.26.4


In [13]:
# 內建型態做轉換

import numpy as np

np.array([1, 2, 3])

array([1, 2, 3])

In [16]:
# 會自動轉換成範圍比較大的型態：

print(np.array([1, 2, 3.0]), np.array([1, 2, 3.0]).dtype)

# 也可以指定成想要的型態：

print(np.array([1, 2, 3], dtype=complex), np.array([1, 2, 3], dtype=complex).dtype)

[1. 2. 3.] float64
[1.+0.j 2.+0.j 3.+0.j] complex128


In [18]:
# 字典型態被轉成陣列不符合期待

print(np.array({0: 123, 1: 456}))
print(np.array({0: 123, 1: 456}).size)
print(np.array({0: 123, 1: 456}).dtype,'\n')

# 正確的寫法應該寫轉成有序的 List 再作轉換

print(np.array(list({0: 123, 1: 456}.items())))
print(np.array(list({0: 123, 1: 456}.items())).size) 
print(np.array(list({0: 123, 1: 456}.items())).dtype) 

{0: 123, 1: 456}
1
object 

[[  0 123]
 [  1 456]]
4
int32


In [19]:
# 從固定大小的初始值開始

print(np.zeros((2, 3)))
print(np.ones((2, 3)))
print(np.full((2, 3), 9))


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[9 9 9]
 [9 9 9]]


In [20]:
# np.zeros 和 np.empty 

print(np.zeros((2, 3)))
print(np.empty((2, 3)))


[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
# 從固定大小的序列值開始

print(np.arange( 10, 30, 5 ))
print(np.linspace( 0, 2, 3 ))
print(np.logspace( 0, 2, 3 ))


[10 15 20 25]
[0. 1. 2.]
[  1.  10. 100.]


In [22]:
## 從固定大小的亂數值開始（新版）

from numpy.random import default_rng
rng = default_rng()

normal = rng.standard_normal((3,2))
random = rng.random((3,2))
integers = rng.integers(0, 10, size=(3,2))

print(normal)
print(random)
print(integers)

[[-2.6056465  -0.70736183]
 [-1.14354893  1.45424545]
 [-1.75877324  1.06090468]]
[[0.02366231 0.07845137]
 [0.68766698 0.68225075]
 [0.35882647 0.62433156]]
[[4 0]
 [0 6]
 [6 9]]


In [23]:
## 從固定大小的亂數值開始（舊版）

normal = np.random.randn(2, 3)
random = np.random.random((3,2))
integers = np.random.randint(0, 10, size=(3,2))

print(normal)
print(random)
print(integers)

[[ 1.55225318 -1.24475286  0.49467782]
 [-0.22221297 -2.39064965 -0.01409046]]
[[0.12796462 0.22540056]
 [0.0590839  0.40543094]
 [0.53999767 0.18714865]]
[[9 8]
 [9 2]
 [5 7]]
